"use client";

import React from "react";
import { FaGithub, FaLinkedinIn } from "react-icons/fa";
import {
  FolderRegular,
  FolderFilled,
  FolderOpenRegular,
  FolderOpenFilled,
  DocumentRegular,
  DocumentFilled,
  DocumentTextRegular,
  DocumentTextFilled,
  PersonRegular,
  PersonFilled,
  SettingsRegular,
  SettingsFilled,
  WindowConsoleRegular,
  WindowConsoleFilled,
  BrainCircuitRegular,
  BrainCircuitFilled,
  SparkleRegular,
  SparkleFilled,
  BriefcaseRegular,
  BriefcaseFilled,
  HatGraduationRegular,
  HatGraduationFilled,
  TrophyRegular,
  TrophyFilled,
  CertificateRegular,
  CertificateFilled,
  MailRegular,
  MailFilled,
  SearchRegular,
  DismissRegular,
  SubtractRegular,
  MaximizeRegular,
  SquareMultipleRegular,
  ArrowDownloadRegular,
  ArrowSyncRegular,
  MoreHorizontalRegular,
  PowerRegular,
  WifiSettingsRegular,
  Speaker2Regular,
  BatteryChargeRegular,
  ClockRegular,
  CalendarRegular,
  AlertRegular,
  DeleteRegular,
  DeleteFilled,
  DesktopRegular,
  DesktopFilled,
  OpenRegular,
  LinkRegular,
  ChevronRightRegular,
  ChevronLeftRegular,
  ChevronUpRegular,
  CheckmarkRegular,
  CheckmarkCircleRegular,
  CheckmarkCircleFilled,
  ErrorCircleRegular,
  ErrorCircleFilled,
  InfoRegular,
  PrintRegular,
  SendRegular,
  NavigationRegular,
  AppsRegular,
  WeatherMoonRegular,
  WeatherSunnyRegular,
  BluetoothRegular,
  LockClosedRegular,
  LockClosedFilled,
  ArrowUpRegular,
  ArrowDownRegular,
  ArrowRightRegular,
  BotRegular,
  BotFilled,
  ArrowResetRegular,
  TagRegular,
  TagFilled,
  BranchForkRegular,
  BranchRegular,
  LayerRegular,
  LayerFilled,
  DeveloperBoardRegular,
  DeveloperBoardFilled,
  PulseRegular,
  FireRegular,
  FireFilled,
  StarRegular,
  StarFilled,
  RibbonRegular,
  RibbonFilled,
  EyeRegular,
  EyeFilled,
  BuildingRegular,
  BuildingFilled,
  LocationRegular,
  LocationFilled,
  ChatRegular,
  ChatFilled,
  HardDriveRegular,
  HardDriveFilled,
  BookOpenRegular,
  BookOpenFilled,
  CodeRegular,
  CodeFilled,
  CodeBlockRegular,
  CodeTextRegular,
  ShieldCheckmarkRegular,
  ShieldCheckmarkFilled,
} from "@fluentui/react-icons";

// Re-export Fluent UI System Icons
export {
  FolderRegular,
  FolderFilled,
  FolderOpenRegular,
  FolderOpenFilled,
  DocumentRegular,
  DocumentFilled,
  DocumentTextRegular,
  DocumentTextFilled,
  PersonRegular,
  PersonFilled,
  SettingsRegular,
  SettingsFilled,
  WindowConsoleRegular,
  WindowConsoleFilled,
  BrainCircuitRegular,
  BrainCircuitFilled,
  SparkleRegular,
  SparkleFilled,
  BriefcaseRegular,
  BriefcaseFilled,
  HatGraduationRegular,
  HatGraduationFilled,
  TrophyRegular,
  TrophyFilled,
  CertificateRegular,
  CertificateFilled,
  MailRegular,
  MailFilled,
  SearchRegular,
  DismissRegular,
  SubtractRegular,
  MaximizeRegular,
  SquareMultipleRegular,
  ArrowDownloadRegular,
  ArrowSyncRegular,
  MoreHorizontalRegular,
  PowerRegular,
  WifiSettingsRegular,
  Speaker2Regular,
  BatteryChargeRegular,
  ClockRegular,
  CalendarRegular,
  AlertRegular,
  DeleteRegular,
  DeleteFilled,
  DesktopRegular,
  DesktopFilled,
  OpenRegular,
  LinkRegular,
  ChevronRightRegular,
  ChevronLeftRegular,
  ChevronUpRegular,
  CheckmarkRegular,
  CheckmarkCircleRegular,
  CheckmarkCircleFilled,
  ErrorCircleRegular,
  ErrorCircleFilled,
  InfoRegular,
  PrintRegular,
  SendRegular,
  NavigationRegular,
  AppsRegular,
  WeatherMoonRegular,
  WeatherSunnyRegular,
  BluetoothRegular,
  LockClosedRegular,
  LockClosedFilled,
  ArrowUpRegular,
  ArrowDownRegular,
  ArrowRightRegular,
  BotRegular,
  BotFilled,
  ArrowResetRegular,
  TagRegular,
  TagFilled,
  BranchForkRegular,
  BranchRegular,
  LayerRegular,
  LayerFilled,
  DeveloperBoardRegular,
  DeveloperBoardFilled,
  PulseRegular,
  FireRegular,
  FireFilled,
  StarRegular,
  StarFilled,
  RibbonRegular,
  RibbonFilled,
  EyeRegular,
  EyeFilled,
  BuildingRegular,
  BuildingFilled,
  LocationRegular,
  LocationFilled,
  ChatRegular,
  ChatFilled,
  HardDriveRegular,
  HardDriveFilled,
  BookOpenRegular,
  BookOpenFilled,
  CodeRegular,
  CodeFilled,
  CodeBlockRegular,
  CodeTextRegular,
  ShieldCheckmarkRegular,
  ShieldCheckmarkFilled,
};

// Official Windows 11 Start Logo (Four-Pane Geometry)
export function Windows11Logo({ className = "w-4 h-4" }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M2.5 2.5H10.5V10.5H2.5V2.5Z" fill="#0078D4" />
      <path d="M13.5 2.5H21.5V10.5H13.5V2.5Z" fill="#0078D4" />
      <path d="M2.5 13.5H10.5V21.5H2.5V13.5Z" fill="#0078D4" />
      <path d="M13.5 13.5H21.5V21.5H13.5V13.5Z" fill="#0078D4" />
    </svg>
  );
}

// Official GitHub Logo Mark
export function GitHubFluentMark({ className = "w-4 h-4" }: { className?: string }) {
  return <FaGithub className={className} />;
}

// Official LinkedIn Logo Mark
export function LinkedInFluentMark({ className = "w-4 h-4" }: { className?: string }) {
  return <FaLinkedinIn className={className} />;
}
